# Generated by Django 2.2.28 on 2022-10-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20221024_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ddaa',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
